### PR TITLE
sgx: update nfd rule

### PR DESCRIPTION
**Pull request by tkatila**

### CODE REVIEW

**Comment by mythi** [comment]
Looks ok but I believe we need 0.27.1-helm.0 chart version to get the SGX chart fixes released

**Comment by tkatila** [comment]
> Looks ok but I believe we need 0.27.1-helm.0 chart version to get the SGX chart fixes released

I hope you mean 0.27.0-helm.0 ?

**Comment by mythi** [comment]
No,it needs to be 0.27.1-helm.0 to make it after 0.27.0 but before 0.27.1 semver

**Comment by tkatila** [comment]
> No,it needs to be 0.27.1-helm.0 to make it after 0.27.0 but before 0.27.1 semver

Right, I'll update this PR. I think I know, finally, understood what's the difference between app version and chart version. :)

**Review by mythi — APPROVED** [review]

**Review by mythi — APPROVED** [review]

**Pull request merged**
