### PR TITLE
Update Intel GPU resource driver to v0.3.0 release

### PR DESCRIPTION
**Pull request by oxxenix**

### CODE REVIEW

**Comment by oxxenix** [comment]
@byako, @eero-t, PTAL

**Review by eero-t — CHANGES_REQUESTED** [review]
This is missing (at least) the CRD updates from v0.3.0, compare for example:
* https://github.com/intel/helm-charts/blob/main/charts/intel-gpu-resource-driver/crds/gpu.resource.intel.com_gpuallocationstates.yaml
* https://github.com/intel/intel-resource-drivers-for-kubernetes/blob/v0.3.0/deployments/gpu/static/crds/gpu.resource.intel.com_gpuallocationstates.yaml

**Review by eero-t — APPROVED** [review]
Reviewed all changes in driver v0.3.0 update [1], and GAS CRD was the only relevant [2] one needing updates => approved.

----

[1] https://github.com/intel/intel-resource-drivers-for-kubernetes/commit/162bbad106f60502adf28957f085035650e450b1#diff-82a0301787005154edf4a70fbadf93dc666178224e3e85fe9bae8b1bcbbc52c7

[2] Alertmanager webhook with its GPU tainting is best left for manual install until it supports also untainting and there's some solution for updating the necessary Alertmanager configs from Helm.

**Comment by eero-t** [comment]
Did not test it, just checked that updates from driver 0.3.0 commit were there.  I was assuming you to review and @oxxenix tests the Helm side.

(After CRD correction, I would assume test would fail if 0.2.0 binaries were used, as they would not match 0.3.0 CRDs...)

**Pull request merged**
