### PR TITLE
Node feature rules for gpu, qat and sgx devices

### PR DESCRIPTION
**Pull request by tkatila**
Also fixes bad indentation for QAT template.

### CODE REVIEW

**Comment by tkatila** [comment]
@obaranov1 & @poussa & @mythi please review

**Comment by tkatila** [comment]
Ping

**Comment by mythi** [comment]
LGTM. I checked it earlier but forgot to reply since I also wanted to comment that in order to get this published you will need to bump the chart versions.

**Comment by poussa** [comment]
We can merge this now and bump the version for all device plugins in another PR.

**Pull request merged**
