### PR TITLE
Update to 0.27.0 release

### PR DESCRIPTION
**Pull request by oxxenix**

### CODE REVIEW

**Review by tkatila — APPROVED** [review]

**Review by tkatila — CHANGES_REQUESTED** [review]
While trying all the plugins, I noticed that the iaa chart is broken.
```
$ helm install iaa .
Error: INSTALLATION FAILED: template: intel-device-plugins-iaa/templates/iaa.yaml:15:26: executing "intel-device-plugins-iaa/templates/iaa.yaml" at <.Values.spec.sharedDevNum>: nil pointer evaluating interface {}.sharedDevNum
```

This fixes it:
```
diff --git a/charts/iaa-device-plugin/templates/iaa.yaml b/charts/iaa-device-plugin/templates/iaa.yaml
index e65826f..52e9270 100755
--- a/charts/iaa-device-plugin/templates/iaa.yaml
+++ b/charts/iaa-device-plugin/templates/iaa.yaml
@@ -12,7 +12,7 @@ metadata:
 spec:
   image: "{{ .Values.image.hub }}/intel-iaa-plugin:{{ .Values.image.tag | default .Chart.AppVersion }}"
   initImage: "{{ .Values.initImage.hub }}/intel-idxd-config-initcontainer:{{ .Values.initImage.tag | default .Chart.AppVersion }}"
-  sharedDevNum: {{ .Values.spec.sharedDevNum }}
+  sharedDevNum: {{ .Values.sharedDevNum }}
   logLevel: {{ .Values.logLevel }}
   nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 4 }}
```

@obaranov1 can you please include that also?

**Review by tkatila — APPROVED** [review]

**Review by poussa — APPROVED** [review]

**Comment by mythi** [comment]
SGX NodeFeatureRule must be updated if initImage is removed

**Comment by tkatila** [comment]
> SGX NodeFeatureRule must be updated if initImage is removed

Like so:
```
diff --git a/charts/sgx-device-plugin/templates/sgx.yaml b/charts/sgx-device-plugin/templates/sgx.yaml
index d998d47..7b2dae0 100644
--- a/charts/sgx-device-plugin/templates/sgx.yaml
+++ b/charts/sgx-device-plugin/templates/sgx.yaml
@@ -25,6 +25,8 @@ spec:
     - name: "intel.sgx"
       labels:
         "intel.feature.node.kubernetes.io/sgx": "true"
+      extendedResources:
+        sgx.intel.com/epc: "@cpu.security.sgx.epc"
       matchFeatures:
         - feature: cpu.cpuid
           matchExpressions:
```
?

**Comment by tkatila** [comment]
PR here: https://github.com/intel/helm-charts/pull/37

**Pull request merged**
